---
- hosts: webserver
  become: True
  tasks:
    - name: Install python pip3
      apt:
        name: python3-pip
        state: present
    - name: Install docker
      apt:
        name: docker
        state: present
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes      # make docker restart when the host reboots
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: Start the container
      docker_container:
        name: jen_ans_doc
        image: "dibsbharatidocker/jen_ans_doc:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
